services:
  narou:
    image: haoling/narou:3.9.0
    command: ["narou", "web", "-np", "33000"]
    volumes:
      - .:/home/narou/novel:cached
    tty: true
    stdin_open: true
    ports:
      - 9200:33000
      - 9201:33001
