name: Docker Image Build and Push

on:
  workflow_dispatch:
    inputs:
      NAROU_VERSION:
        type: text
        required: true
        description: narouのバージョン https://rubygems.org/gems/narou/versions
      AOZORAEPUB3_VERSION:
        type: text
        required: true
        default: 1.1.1b24Q
      

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: haoling/narou:${{ inputs.NAROU_VERSION }}
        build-args:
          NAROU_VERSION: ${{ inputs.NAROU_VERSION }}
          AOZORAEPUB3_VERSION: ${{ inputs.AOZORAEPUB3_VERSION }}
